### Designing a Neural Networks

In [22]:
import torch.nn as nn
import torch as tr

#create input_tensor with three features
input_tensor=tr.tensor([[0.3471,0.4547,-0.2356]])

#define our linear lyaer
linear_lyaer=nn.Linear(
    in_features=3,

    out_features=2
)

#pass input through linear lyaer
output=linear_lyaer(input_tensor)
print(output)

#weight
print(linear_lyaer.weight)
print("_________________________________________________________________")
#biases
print(linear_lyaer.bias)

tensor([[0.2629, 0.2193]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.5441,  0.3167, -0.3047],
        [ 0.3728,  0.2639,  0.4053]], requires_grad=True)
_________________________________________________________________
Parameter containing:
tensor([0.2359, 0.0653], requires_grad=True)


In [23]:
# creat network three linear layers
n_features=10
n_classes=3
model=nn.Sequential(
    nn.Linear(n_features,8),#n_features reprsents number of input features
    nn.Linear(8,4),
    nn.Linear(4,n_classes)#n_classes reprsents the number of output classes
)

print(model)

#create ntework with three linear layers 
model=nn.Sequential(
    nn.Linear(10,18),
    nn.Linear(18,20),
    nn.Linear(20,5)
)
print("__________________________________________________________________")
print(model)

Sequential(
  (0): Linear(in_features=10, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=3, bias=True)
)
__________________________________________________________________
Sequential(
  (0): Linear(in_features=10, out_features=18, bias=True)
  (1): Linear(in_features=18, out_features=20, bias=True)
  (2): Linear(in_features=20, out_features=5, bias=True)
)


In [24]:
import torch.nn as nn 

mod=nn.Sequential(
    nn.Linear(8,4),
    nn.Linear(4,2)
    
)
print(mod)
total=0
for parameters in model.parameters():
    total+=parameters.numel()

print(total)

Sequential(
  (0): Linear(in_features=8, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=2, bias=True)
)
683


In [25]:
import torch
import torch.nn as nn

input_tensour=([[6]])
sigmoid=nn.Sigmoid()

output=sigmoid(input_tensor)
print(output)

tensor([[0.5859, 0.6118, 0.4414]])


In [26]:
model=nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1),
    nn.Sigmoid()
)

print(model)

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=1, bias=True)
  (2): Sigmoid()
)


In [27]:
import torch 
import torch.nn as nn 

input_tensor=torch.tensor(
    [[4.3,6.1,2.3]]
)

probablities=nn.Softmax(dim=1) # indictes softmax is applied to the input tensor's last dimension 
output_tensor=probablities(input_tensor)
print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


### Forward Pass
##### possible output
###### 1-Binary classification 
###### 2-multi-class classification
###### 3-regressionn

### First: Binary Classification

In [33]:
# Create input data of shape 5x6
input_data = torch.tensor(
    [[-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
     [-0.9155, -0.0475, -1.3645, 0.6356, -1.9520, -0.3398],
     [ 0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0653],
     [-1.6630, -0.0718, -0.1285, 0.5396, -0.8288, -0.8622],
     [-0.7413, 1.7920, -0.0883, -0.6685, 0.4745, -0.4245]]
)

#creat binary classification model
model=nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1),
    nn.Sigmoid()

)
print(model)
print("__________________________________________")

#pass input data through model 
output=model(input_data)
print(output)

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=1, bias=True)
  (2): Sigmoid()
)
__________________________________________
tensor([[0.5625],
        [0.5691],
        [0.5239],
        [0.5650],
        [0.6115]], grad_fn=<SigmoidBackward0>)


### Secondly:Multi-Class Classification

In [39]:
n_classes=3
#creat multi-class classification model 
model=nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1),
    nn.Softmax(dim=-1)
)
print(model)
print("____________________________________")

#pass input data through model 
output=model(input_data)
print(output.shape)
print("_______________________________________")
print(output)

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=1, bias=True)
  (2): Softmax(dim=-1)
)
____________________________________
torch.Size([5, 1])
_______________________________________
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>)


### Thied:Regression

In [42]:
#creat regression model
model=nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1)
)
print(model)
print("______________________________")

# pass input data through model 
output=model(input_data)

# return output
input(output)

Sequential(
  (0): Linear(in_features=6, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=1, bias=True)
)
______________________________


tensor([[0.7085],
        [0.5490],
        [0.6103],
        [0.5743],
        [0.7096]], grad_fn=<AddmmBackward0>) vcx


'vcx'